### ISSUE TITLE
起動時エラー１

### ISSUE THREAD

**Issue by aaartas** [aaartas/nestjs-app#1]
以下実行時にエラーが出る
```
> yarn start:dev
```

# ググる前

```
[Nest] 32652  - 2022/07/05 20:15:40   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "aurora-data-api",...
```
**解読**
- [TypeOrmModule]において、データベースに繋げない。
- MissingDriverError: Wrong driver: "undefined" given.
    - ドライバが「undefined」になっている
    - yarn typeorm ...を使ったときは、ドライバはormconfig.jsonで指定している「mysql」になっていた。

**自分の考察**
 - undefinedになってるのが原因っぽいが、どうすべきか自分では分からない。
 - エラー1と2はつながっている可能性もある
→エラー1を直しても依然消えない。これらは独立していることが判明

# ググる
 1.順に対処していく https://github.com/typeorm/typeorm/issues/4068
 1-a.「ormconfig.tsで次のように構成をエクスポートすることで解決しました。」
`   export = ORMConfig`
→今回の設定ファイルはormconfig.jsonなので、exportできないしおそらく不要(?)

1-b.「For me there was needed also to configure "typeorm" script as described in typeorm [instruction]」＝「私にとっては、typeorm instructionで説明されているように「typeorm」スクリプトを構成する必要もありました。」
→公式サイトのtypeorm instruction（https://typeorm.io/using-cli#installing-cli）を見て確認してみる

・エンティティファイルはtsなので、ts-nodeの導入が必要
→すでにインストールされている。
```
❯ npm ts-node -v
7.24.0
```
- package.jsonのscriptsセクションにtypeormコマンドを追加します
→以下の記述がなかった。これが原因かも、再実行
```
"scripts": {
    ...
    "typeorm": "typeorm-ts-node-commonjs"
}
```
→エラー消えず。

0-a.以下のミスを発見、修正（jsじゃなくてts）
` "entities": ["dist/entities/**/*.entity.js"],
  "migrations": ["dist/migrations/**/*.js"],`
→消えず。

**考察**
0-b.[TypeOrmModule]でエラーが起きている
→TypeOrmModuleに、ormconfig.jsonで設定した`"type": "mysql",`が行き届いていない？

Q.TyperOrmModuleとormconfig.jsonはどうつながっているのか

TypeOrmModuleクラスを定義しているファイルで、ormconfig.jsonをインポートしてみる
typeorm.module.d.ts
```
import ...
import ormconfig from  '@src/ormconfig.json'; //追加

export declare class TypeOrmModule {
    static forRoot(options?: TypeOrmModuleOptions): DynamicModule;
    static forFeature(entities?: EntityClassOrSchema[], dataSource?: DataSource | DataSourceOptions | string): DynamicModule;
    static forRootAsync(options: TypeOrmModuleAsyncOptions): DynamicModule;
}
```
→消えず。

#質問する
## 対処１
近藤くんのコメント参照。

→以下エラーが出る。
```
[Nest] 10449  - 2022/07/11 8:23:56   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: connect ECONNREFUSED 127.0.0.1:3306
```

ちなみに、ormconfig.jsonは読み込まれていなかった。jsonでのみportを3000にしても上記エラー(3306)が出たため

**原因と対処調査**
以下、似た現象
https://teratail.com/questions/237462

ベストアンサーが参考になりそう。まずCLIでMySQLが起動出来るか確認
`mysql -uroot -p[password]`
→起動できなくなっている。(以前はこれでできた)
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)`

以下参考。serverが起動できていないのが原因だった。
https://qiita.com/hondy12345/items/d32ed749fb49e9da7de6

```
❯ mysql.server restart
 ERROR! MySQL server process #12545 is not running!
Starting MySQL
... SUCCESS! 

~/Desktop/programing/learn/nest-js master*
❯ mysql -uroot -pradwimps123
```

**再度以下を実行すると、エラーは消えた**
`> yarn start:dev`

# 学んだこと
- 記事によって公式サイトと記述方法が異なる場合があるので、詰まったら一度公式サイトの該当箇所を探して比較してみる
- 3306はMySQLのポート番号で、そこに yarn start から繋げない場合、まず mysql で起動出来るか確認してみる

**Comment by TOMOFUMI-KONDO** [comment]
まず複数のエラーについてひとつのissueに書かないでほしい。読みづらい

**Comment by TOMOFUMI-KONDO** [comment]
> 0-a.以下のミスを発見、修正（jsじゃなくてts）
"entities": ["dist/entities/**/*.entity.js"], "migrations": ["dist/migrations/**/*.js"],

これはdist以下を指定してるからjsで良いと思う。

**Comment by TOMOFUMI-KONDO** [comment]
https://docs.nestjs.com/techniques/database

ormconfig.jsonの設定読み込まれてなさそうだったから

```.ts
@Module({
  imports: [
    TypeOrmModule.forRoot({
      type: 'mysql',
      host: '127.0.0.1',
      port: 3306,
      username: 'root',
      password: 'root',
      database: 'todolist',
      entities: ['dist/entities/**/*.entity.js'],
      migrations: ['dist/migrations/**/*.js'],
      migrationsTableName: 'custom_migration_table',
      logging: false,
    }),
    TaskModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

こんな感じに書いたら動いた

Nestjsの公式Docではormconfig.json使った設定書いてなかったけど、どこから拾ってきた？

**Comment by aaartas** [comment]
なるほど、一旦それで試してみる。

> Nestjsの公式Docではormconfig.json使った設定書いてなかったけど、どこから拾ってきた？
参考にしてた題材のサイトから拾ってきた。
https://zenn.dev/chida/articles/bba2b5346414ed#typeorm%E3%81%A8db%E3%81%AE%E8%A8%AD%E5%AE%9A
